# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Nightly version checks

on:
  schedule:
    - cron: '0 1 * * 1-5'  # 01:00 AM UTC Monday - Friday
  workflow_dispatch: {}
jobs:
  redpanda-version:
    strategy:
      matrix:
        chart:
          - redpanda
          - console
          - operator
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git checkout main
          git checkout -
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.3'
      - uses: dcarbone/install-yq-action@64b1b9eb28920bb1a4c13c05321df284f9a8f940  # v1.1.1
      - run: go install github.com/joejulian/docker-tag-list@latest
      - name: Check chart version for ${{ matrix.chart }}
        id: chartversion
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          {
            echo 'MESSAGE<<EOF'
            .github/bump_chart_versions.sh ${{ matrix.chart }}
            echo -e '\nEOF'
          } >> "$GITHUB_OUTPUT"
      - name: debug -- delete me
        run: echo ${{ steps.chartversion.output.MESSAGE }}
      - name: create PR
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38  # v5.0.2
        with:
          commit-message: ${{ steps.chartversion.outputs.MESSAGE }}
          title: ${{ steps.chartversion.outputs.MESSAGE }}
          branch: bump-appversion/${{ matrix.chart }}
